### PR TITLE
Small refactoring of src/Core/

### LINKED ISSUE #1: general remarks
I don't feel confident enough in writing a PR since there are no tests for me to run & check if I broke stuff.

[Src/Shared/Config](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Config.cpp)

- the spacing in the file seems **very* inconsistent (why so many blank lines?)
- define/undefine macros directly in that file, not in `configVariables.h` (don't `ifndef` there).
- inline-included files usually don't use ".h" in C++. [`.inl` is a widely-used extension](http://stackoverflow.com/questions/1208028/significance-of-a-inl-file-in-c)
- [your destructor can be defaulted](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Config.cpp#L24). (`class A { ~A() = default; };`)
- C++ has other APIs for opening files, other than `fopen/fseek/ftell`/etc, but maybe that's for performance reasons? (Even then, you should try to use some other construct to get RAII `fclose`)
- [You don't need a `return;` after a `throw;`](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Config.cpp#L48)
- [There's a function to check if a char is a space](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Config.cpp#L75), it's [`std::isspace`](http://en.cppreference.com/w/cpp/string/byte/isspace)
- [Checking if a character is in a range](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Config.cpp#L110-L113) is usally easier done with [`std::strchr`](http://en.cppreference.com/w/cpp/string/byte/strchr), i.e.: `std::strchr("aeiouy", c) != nullptr`
- Don't use `NULL`. use `nullptr`.
- Don't use `strcmp`. Use `std::string`.
- Use RAII instead of raw arrays (so that you can lose the `delete[]`).
- `sizeof(char)` is 1, as per standard (`sizeof` returns the number of chars you can stuff in one type... so it's always gonna be 1 for char)

[Src/Shared/Core/Active](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Active.cpp)
- if you can "afford" `std::make_unique`, use it (no big deal anyways).
- [`foo == false`](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Active.cpp#L53) is better expressed as `!foo`.
- any reason to `catch (...)` and assigning the exception, inside of using your destructor with `std::uncaught_exception(s)` (the behavior of either is very different, and the second one is C++17 only)? The problem is that this is dangerous... on windows, you can catch a lot more than you might first except if SEH exceptions are enabled - that includes access violations...
- don't use `NULL`; use `nullptr`
- [any code after `std::rethrow_exception` is dead code /!\ ](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Active.cpp#L94)

[Src/Shared/Core/Exception](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Exception.cpp)
- you can default your destructors.

[Src/Shared/Core/Logger](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Logger.cpp)
- don't take a `std::string&&` to forward it. Either do that, and `std::move`, or just do it the "simple" way: take it by value (and then move it).
- `CLog::Log` takes the text by rvalue reference, but then copies the value inside the lambda. If you enabled C++14, take it by value and use `[Text=std::move(Text)]() { ... }` to move it inside the lambda.
- [`auto a = std::string{};`](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Logger.cpp#L63) really is just `std::string a;`
- [why do you convert your string to a c_str to call Write?](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Logger.cpp#L150)
- `sizeof(char)` is 1.

[Src/Shared/Core/StringUtil](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/StringUtil.cpp)
- If you take your param by non-const ref, don't return it as well. (especially since your 2nd overload doesn't use the return value). That's true for split's first overload, and for the trim functions

[Src/Shared/Core/Threading](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Threading.cpp)
- That's some pretty... hairy code? I mean, mutexes named `L N M` makes it pretty hard (for me) to reason through it. I'm not sure you couldn't use some C++11/C++14/Boost mutex type? (C++17 and Boost both have a shared mutex impl (i.e. multi reader, only one writer)).
- [When you know the size you need, you can `.reserve` enough space](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Threading.cpp#L154).
- [it doesn't make sense to move the return of a function](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Core/Threading.cpp#L181). It's already a rvalue -- the compiler will do the moving for you. (yeah, the rules are really complex...).
- you don't need a new scope for that last `unique_ptr` in "StartThreads" since RAII works LIFO (last in, first out).

[Src/Shared/Network/DatabaseConnection](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Network/DatabaseConnection.cpp).
- you could move all your string parameters in the constructor
- instead of using `new MYSQL`, use a `unique_ptr` with a custom deleter (that's gonna be `mysql_close`). You can remove all the delete this way (and use `.reset()` where needed).
- use `nullptr` instead of `NULL`.
- `while (a != 0)` is `while (a)`

[Src/Shared/Network/QueryResult](https://github.com/ppy/osu-performance/blob/d8db495725f6c0e3a13000ecac65fbe73ec1e730/Src/Shared/Network/QueryResult.cpp)
- use `nullptr` instead of `NULL`.

That's pretty much all I saw for Src/Shared. I'll try to look at other files tomorrow :)

### PR DESCRIPTION
**Pull request by vendethiel**
Sorry for the delay! I thought this didn't compile at all, but #6 prompted me to try again.

This compiles locally (`cmake CMakeLists.txt && make` in the root directory)

Resolves #1 (well, not *entirely*, but mostly).

### CODE REVIEW

File: Src/Shared/Core/Active.cpp [hunk 1]
```diff
@@ -88,14 +88,14 @@ void CActive::CheckForAndThrowException() const
 {
 	if(_isDone)
 	{
-		if(_activeException)
+		if (std::exception_ptr exception = _activeException)
```
Comment (Tom94) [inline Src/Shared/Core/Active.cpp]: Wow, I was not aware variable declarations inside if-conditions where already a thing.

Comment (vendethiel) [inline Src/Shared/Core/Active.cpp]: not quite the same as what's coming in C++.

It's actually a special case in the standard:
http://eel.is/c++draft/stmt.select#1
